# Generated by Django 4.2.1 on 2023-05-15 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPAdresleri',
            fields=[
                ('ip_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ip_adresi', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Ports',
            fields=[
                ('port_id', models.IntegerField(primary_key=True, serialize=False)),
                ('port', models.IntegerField(max_length=5)),
                ('ip_adresi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.ipadresleri')),
            ],
        ),
    ]
