# Generated by Django 4.2.1 on 2023-05-16 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ports',
            old_name='ip_adresi',
            new_name='ip_adresi_id',
        ),
    ]
