# Generated by Django 4.2.1 on 2023-05-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_rename_ip_adresi_ports_ip_adresi_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipadresleri',
            name='ip_adresi',
            field=models.TextField(max_length=15),
        ),
    ]
