# Generated by Django 4.2.1 on 2023-05-16 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_alter_ipadresleri_ip_adresi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ports',
            old_name='ip_adresi_id',
            new_name='ip_adresi',
        ),
    ]
