# Generated by Django 4.2.1 on 2023-05-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_rename_ip_adresi_id_ports_ip_adresi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipadresleri',
            name='ip_adresi',
            field=models.CharField(max_length=15),
        ),
    ]
