# Generated by Django 4.2.1 on 2023-05-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_alter_ipadresleri_ip_adresi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ports',
            name='port',
            field=models.CharField(max_length=5),
        ),
    ]
