# Generated by Django 4.2.1 on 2023-05-18 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0007_alter_ipadresleri_ip_id_alter_ports_port_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipadresleri',
            name='tarih',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2023, 5, 18, 12, 24, 17, 292171, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
