# Generated by Django 4.2.1 on 2023-05-20 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0009_remove_ipadresleri_tarih'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipadresleri',
            name='islem_tarihi',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 5, 20, 9, 58, 56, 285946, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
