# Generated by Django 4.2.1 on 2023-05-26 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0011_ports_servis_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ports',
            name='servis_name',
        ),
    ]
