# Generated by Django 4.2.1 on 2023-05-26 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0012_remove_ports_servis_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ports',
            name='servis_name',
            field=models.CharField(default=datetime.datetime(2023, 5, 26, 11, 47, 56, 693280, tzinfo=datetime.timezone.utc), max_length=20),
            preserve_default=False,
        ),
    ]
