# Generated by Django 4.2.1 on 2023-05-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0013_ports_servis_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scapy_Veri',
            fields=[
                ('icerik_id', models.AutoField(primary_key=True, serialize=False)),
                ('icerik', models.TextField()),
            ],
        ),
    ]
